### ISSUE TITLE
Blank page when running this app

### ISSUE THREAD

**Issue by wassimj** [napoles-uach/Pyvista_streamlit#2]
Hello
I am getting a blank page when running this app. I cannot get the pyvista component to display. You had said you got it working on the cloud. May I know how you did that? Thank you!

**Comment by napoles-uach** [comment]
Hi @wassimj, you can clone this repo and launch it on [Streamlit cloud](https://streamlit.io/cloud). Here is the app running, and you should get the same:
https://napoles-uach-pyvista-streamlit-app-s9bt3a.streamlitapp.com/ 

If running locally, please ensure that you have installed the packages in the requirements.txt and packages.txt files.

Let me know if this works for you! Btw, this code first creates a html file that is opened with components.html, so first ensure that this file is available in the same folder as your app.py file.

**Comment by wassimj** [comment]
Hi. When I run your app from the link that you provided, it works. However, when I clone your repo and deploy it on Streamlit Cloud, it gives me a blank page and reports:

```
/home/appuser/venv/lib/python3.9/site-packages/pyvista/plotting/plotting.py:116: UserWarning: 

This system does not appear to be running an xserver.

PyVista will likely segfault when rendering.


Try starting a virtual frame buffer with xvfb, or using

  ``pyvista.start_xvfb()``


  warnings.warn(
```

**Comment by wassimj** [comment]
Here is the link to the cloned app: https://wassimj-pyvista-streamlit-app-2t4sbj.streamlitapp.com/

**Comment by napoles-uach** [comment]
It is weird as I just launched the app in Streamlit Cloud to answer you in my previous reply. I'm not sure of what is failing. I think this is more related to Pyvista than to Streamlit. I'll try to make it work and let you know if I have success.

**Comment by napoles-uach** [comment]
Hey @wassimj there is a new component that works with pyvista:
https://github.com/edsaac/streamlit-PyVista-viewer

hope that helps!

**Comment by wassimj** [comment]
Many thanks. Will try it
